name: CI/CD

on:
  push:
  workflow_dispatch:

jobs:
  ci/cd:
    name: Copy repository
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Copy repository to remote
        uses: appleboy/scp-action@v0.1.7
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          source: "./,!.git"
          target: ${{ env.PATH || '/var/www/html' }}

      - name: Restart Apache
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart apache2
